// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dotR_hypergeo_cpp
double dotR_hypergeo_cpp(int k_drawn, int n_draws, int K_successes_in_pop, int N_total_items_in_pop);
RcppExport SEXP _dotR_dotR_hypergeo_cpp(SEXP k_drawnSEXP, SEXP n_drawsSEXP, SEXP K_successes_in_popSEXP, SEXP N_total_items_in_popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k_drawn(k_drawnSEXP);
    Rcpp::traits::input_parameter< int >::type n_draws(n_drawsSEXP);
    Rcpp::traits::input_parameter< int >::type K_successes_in_pop(K_successes_in_popSEXP);
    Rcpp::traits::input_parameter< int >::type N_total_items_in_pop(N_total_items_in_popSEXP);
    rcpp_result_gen = Rcpp::wrap(dotR_hypergeo_cpp(k_drawn, n_draws, K_successes_in_pop, N_total_items_in_pop));
    return rcpp_result_gen;
END_RCPP
}
// dotR_betabin_cpp
double dotR_betabin_cpp(int k, int n, double p, double theta);
RcppExport SEXP _dotR_dotR_betabin_cpp(SEXP kSEXP, SEXP nSEXP, SEXP pSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(dotR_betabin_cpp(k, n, p, theta));
    return rcpp_result_gen;
END_RCPP
}
// dotR_dnadot_mde_cpp
List dotR_dnadot_mde_cpp(IntegerMatrix genotypes_locus, int n_individuals, int n_subsample_individuals, NumericVector N_try_values, NumericVector p_try_values, int target_allele_idx, String discrepancy_type, double reg_strength, double reg_N_threshold, bool debug);
RcppExport SEXP _dotR_dotR_dnadot_mde_cpp(SEXP genotypes_locusSEXP, SEXP n_individualsSEXP, SEXP n_subsample_individualsSEXP, SEXP N_try_valuesSEXP, SEXP p_try_valuesSEXP, SEXP target_allele_idxSEXP, SEXP discrepancy_typeSEXP, SEXP reg_strengthSEXP, SEXP reg_N_thresholdSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes_locus(genotypes_locusSEXP);
    Rcpp::traits::input_parameter< int >::type n_individuals(n_individualsSEXP);
    Rcpp::traits::input_parameter< int >::type n_subsample_individuals(n_subsample_individualsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_try_values(N_try_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_try_values(p_try_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type target_allele_idx(target_allele_idxSEXP);
    Rcpp::traits::input_parameter< String >::type discrepancy_type(discrepancy_typeSEXP);
    Rcpp::traits::input_parameter< double >::type reg_strength(reg_strengthSEXP);
    Rcpp::traits::input_parameter< double >::type reg_N_threshold(reg_N_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(dotR_dnadot_mde_cpp(genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, discrepancy_type, reg_strength, reg_N_threshold, debug));
    return rcpp_result_gen;
END_RCPP
}
// dotR_dnadot_bhd_cpp
List dotR_dnadot_bhd_cpp(IntegerMatrix genotypes_locus, int n_individuals, int n_subsample_individuals, NumericVector N_try_values, NumericVector p_try_values, int target_allele_idx, int bhd_buffer_width);
RcppExport SEXP _dotR_dotR_dnadot_bhd_cpp(SEXP genotypes_locusSEXP, SEXP n_individualsSEXP, SEXP n_subsample_individualsSEXP, SEXP N_try_valuesSEXP, SEXP p_try_valuesSEXP, SEXP target_allele_idxSEXP, SEXP bhd_buffer_widthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes_locus(genotypes_locusSEXP);
    Rcpp::traits::input_parameter< int >::type n_individuals(n_individualsSEXP);
    Rcpp::traits::input_parameter< int >::type n_subsample_individuals(n_subsample_individualsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_try_values(N_try_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_try_values(p_try_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type target_allele_idx(target_allele_idxSEXP);
    Rcpp::traits::input_parameter< int >::type bhd_buffer_width(bhd_buffer_widthSEXP);
    rcpp_result_gen = Rcpp::wrap(dotR_dnadot_bhd_cpp(genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, bhd_buffer_width));
    return rcpp_result_gen;
END_RCPP
}
// dotR_dnadot_betabin_cpp
List dotR_dnadot_betabin_cpp(IntegerMatrix genotypes_locus, int n_individuals, int n_subsample_individuals, NumericVector N_try_values, NumericVector p_try_values, int target_allele_idx, double global_fis);
RcppExport SEXP _dotR_dotR_dnadot_betabin_cpp(SEXP genotypes_locusSEXP, SEXP n_individualsSEXP, SEXP n_subsample_individualsSEXP, SEXP N_try_valuesSEXP, SEXP p_try_valuesSEXP, SEXP target_allele_idxSEXP, SEXP global_fisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes_locus(genotypes_locusSEXP);
    Rcpp::traits::input_parameter< int >::type n_individuals(n_individualsSEXP);
    Rcpp::traits::input_parameter< int >::type n_subsample_individuals(n_subsample_individualsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_try_values(N_try_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_try_values(p_try_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type target_allele_idx(target_allele_idxSEXP);
    Rcpp::traits::input_parameter< double >::type global_fis(global_fisSEXP);
    rcpp_result_gen = Rcpp::wrap(dotR_dnadot_betabin_cpp(genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, global_fis));
    return rcpp_result_gen;
END_RCPP
}
// dotR_dnadot_betabin_dynamic_cpp
List dotR_dnadot_betabin_dynamic_cpp(IntegerMatrix genotypes_locus, int n_individuals, int n_subsample_individuals, NumericVector N_try_values, NumericVector p_try_values, int target_allele_idx, double migration_rate_m);
RcppExport SEXP _dotR_dotR_dnadot_betabin_dynamic_cpp(SEXP genotypes_locusSEXP, SEXP n_individualsSEXP, SEXP n_subsample_individualsSEXP, SEXP N_try_valuesSEXP, SEXP p_try_valuesSEXP, SEXP target_allele_idxSEXP, SEXP migration_rate_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type genotypes_locus(genotypes_locusSEXP);
    Rcpp::traits::input_parameter< int >::type n_individuals(n_individualsSEXP);
    Rcpp::traits::input_parameter< int >::type n_subsample_individuals(n_subsample_individualsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_try_values(N_try_valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_try_values(p_try_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type target_allele_idx(target_allele_idxSEXP);
    Rcpp::traits::input_parameter< double >::type migration_rate_m(migration_rate_mSEXP);
    rcpp_result_gen = Rcpp::wrap(dotR_dnadot_betabin_dynamic_cpp(genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, migration_rate_m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dotR_dotR_hypergeo_cpp", (DL_FUNC) &_dotR_dotR_hypergeo_cpp, 4},
    {"_dotR_dotR_betabin_cpp", (DL_FUNC) &_dotR_dotR_betabin_cpp, 4},
    {"_dotR_dotR_dnadot_mde_cpp", (DL_FUNC) &_dotR_dotR_dnadot_mde_cpp, 10},
    {"_dotR_dotR_dnadot_bhd_cpp", (DL_FUNC) &_dotR_dotR_dnadot_bhd_cpp, 7},
    {"_dotR_dotR_dnadot_betabin_cpp", (DL_FUNC) &_dotR_dotR_dnadot_betabin_cpp, 7},
    {"_dotR_dotR_dnadot_betabin_dynamic_cpp", (DL_FUNC) &_dotR_dotR_dnadot_betabin_dynamic_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_dotR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
