# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Hypergeometric Probability (Stable Version)
#' @keywords internal
dotR_hypergeo_cpp <- function(k_drawn, n_draws, K_successes_in_pop, N_total_items_in_pop) {
    .Call(`_dotR_dotR_hypergeo_cpp`, k_drawn, n_draws, K_successes_in_pop, N_total_items_in_pop)
}

#' Calculate Beta-binomial Probability
#' @keywords internal
dotR_betabin_cpp <- function(k, n, p, theta) {
    .Call(`_dotR_dotR_betabin_cpp`, k, n, p, theta)
}

#' Minimum Distance Estimation (MDE) Core Logic (C++ Core Logic)
#' @keywords internal
dotR_dnadot_mde_cpp <- function(genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, discrepancy_type, reg_strength, reg_N_threshold, debug = FALSE) {
    .Call(`_dotR_dotR_dnadot_mde_cpp`, genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, discrepancy_type, reg_strength, reg_N_threshold, debug)
}

#' Buffered Histogram Discrepancy (BHD) Method (C++ Core Logic)
#' @keywords internal
dotR_dnadot_bhd_cpp <- function(genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, bhd_buffer_width) {
    .Call(`_dotR_dotR_dnadot_bhd_cpp`, genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, bhd_buffer_width)
}

#' MDE using Beta-binomial distribution (Fixed Fis)
#' @keywords internal
dotR_dnadot_betabin_cpp <- function(genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, global_fis) {
    .Call(`_dotR_dotR_dnadot_betabin_cpp`, genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, global_fis)
}

#' --- NEW FUNCTION ---
#' MDE using Beta-binomial distribution (Dynamic Fis)
#' @keywords internal
dotR_dnadot_betabin_dynamic_cpp <- function(genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, migration_rate_m) {
    .Call(`_dotR_dotR_dnadot_betabin_dynamic_cpp`, genotypes_locus, n_individuals, n_subsample_individuals, N_try_values, p_try_values, target_allele_idx, migration_rate_m)
}

